"""add salon model and salon_id

Revision ID: 770b2a170f8f
Revises: 96c314c55d0d
Create Date: 2026-09-17 16:33:20.194872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '770b2a170f8f'
down_revision: Union[str, Sequence[str], None] = '96c314c55d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salons_id'), 'salons', ['id'], unique=False)
    op.create_index(op.f('ix_salons_slug'), 'salons', ['slug'], unique=True)
    op.add_column('bookings', sa.Column('salon_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bookings', 'salons', ['salon_id'], ['id'])
    op.add_column('services', sa.Column('salon_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'services', 'salons', ['salon_id'], ['id'])
    op.add_column('staff', sa.Column('salon_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'staff', 'salons', ['salon_id'], ['id'])
    op.add_column('user', sa.Column('salon_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('role', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'user', 'salons', ['salon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.drop_column('user', 'salon_id')
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_column('staff', 'salon_id')
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'salon_id')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'salon_id')
    op.drop_index(op.f('ix_salons_slug'), table_name='salons')
    op.drop_index(op.f('ix_salons_id'), table_name='salons')
    op.drop_table('salons')
    # ### end Alembic commands ###
