"""rename fullname to full_name

Revision ID: 96c314c55d0d
Revises: 6f503338b820
Create Date: 2026-08-29 15:49:57.698028

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96c314c55d0d"
down_revision: str | Sequence[str] | None = "6f503338b820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=False))
    op.drop_column("user", "fullname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("fullname", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("user", "full_name")
    # ### end Alembic commands ###
