"""add deposit settings to salon

Revision ID: a066ac7e7fc4
Revises: 770b2a170f8f
Create Date: 2026-09-22 15:14:26.738908

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a066ac7e7fc4'
down_revision: str | Sequence[str] | None = '770b2a170f8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salons', sa.Column('deposit_enabled', sa.Boolean(), nullable=True))
    op.add_column('salons', sa.Column('deposit_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salons', 'deposit_percentage')
    op.drop_column('salons', 'deposit_enabled')
    # ### end Alembic commands ###
